name: SOOP Live Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행 (최소 5분)
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - name: Run node soop.js
        run: node soop.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

      - name: Save Status
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add status.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "update status" && git push)
